**Row Swap**

In [ ]:
import numpy as np

In [ ]:
def swaprow(i, j, A):
  tmp = A[i, :]                         # address of tmp and A[i,:] are same
  A[i, :] = A[j, :]                     # A[i,:]= A[j,:]  just means tmp = A[j,:]
  A[j, :] = tmp                         # this means A[j,:] = tmp = A[i,:] = [7,8,9]
  return A

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
swaprow(1,2,A)

array([[1, 2, 3],
       [7, 8, 9],
       [7, 8, 9]])

In [ ]:
# to solve the problem we could use built-in function

def swaprow_1(i, j, A):
  A[[i,j]] = A[[j,i]]
  return A

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
swaprow_1(1,2,A)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])