In [204]:
import numpy as np
from scipy.linalg import svd, qr
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

In [205]:
np.linalg.matrix_rank(A)

2

In [206]:
Col_vec, sing_val, range_vec = svd(A)

In [207]:
Col_vec

array([[ 2.66235859e-01,  1.70641342e-01,  9.48683298e-01],
       [ 5.39615303e-01, -8.41911709e-01, -5.55111512e-17],
       [-7.98707576e-01, -5.11924025e-01,  3.16227766e-01]])

In [208]:
range_vec

array([[ 0.21009764, -0.42019527,  0.72119431, -0.50909104],
       [ 0.0053474 , -0.01069481, -0.58183848, -0.81321646],
       [-0.24209024, -0.89711712, -0.29564648,  0.22173486],
       [ 0.9472184 , -0.13602362, -0.23224108,  0.17418081]])

In [209]:
sing_val

array([1.78088115e+01, 4.22448020e+00, 3.71370969e-16])

In [210]:
print('we can clearly see that there are 3 non- zero singular values but rank is 2, assume the third singular value to be 0 as it is almost close to machine precision')

we can clearly see that there are 3 non- zero singular values but rank is 2, assume the third singular value to be 0 as it is almost close to machine precision


In [211]:
Col_vect_QR,R1 = qr(A)

In [212]:
Col_vect_QR

array([[-0.26726124,  0.95618289, -0.11952286],
       [-0.53452248, -0.04390192,  0.84401323],
       [ 0.80178373,  0.28945968,  0.52283453]])

In [213]:
R1

array([[-3.74165739e+00,  7.48331477e+00, -1.28285396e+01,
         9.08688223e+00],
       [ 0.00000000e+00, -1.98602732e-15, -1.31705767e-01,
        -1.75607689e-01],
       [ 0.00000000e+00,  0.00000000e+00,  2.53203970e+00,
         3.37605293e+00]])

In [221]:
# col_check= np.array([[-0.26726124, -0.53452248,  0.80178373],
# [ 0.95618289, -0.04390192,  0.28945968],
# [-0.26726124, -0.53452248,  0.80178373],
# [ 0.95618289, -0.04390192,  0.28945968],
# [-0.26726124, -0.53452248,  0.80178373],
# [ 0.95618289, -0.04390192,  0.28945968]])
col_check = np.zeros((3,4))
for i in range(4):
  if i<2:
    col_check[:,i] = Col_vec[:,i]
  else:
    col_check[:,i] = Col_vect_QR[:,i-2]

In [222]:
col_check

array([[-0.26726124, -0.53452248,  0.80178373],
       [ 0.95618289, -0.04390192,  0.28945968],
       [-0.26726124, -0.53452248,  0.80178373],
       [ 0.95618289, -0.04390192,  0.28945968],
       [-0.26726124, -0.53452248,  0.80178373],
       [ 0.95618289, -0.04390192,  0.28945968]])

In [223]:
np.linalg.matrix_rank(col_check)

2

In [224]:
print('We took first 2 vectors of SVD Decomposition and first 2 vector of QR Decomposition and finds its rank which is 2, shows that both span same coloumn space ')

We took first 2 vectors of SVD Decomposition and first 2 vector of QR Decomposition and finds its rank which is 2, shows that both span same coloumn space 


In [ ]:
import time
time1 = 0
time2 = 0
for i in range(10000):
  start_time = time.time()
  A1 = np.random.random((500,500))
  u,s,v = svd(A)
  end_time = datetime.now()
  time1 += time.time() - start_time
  start_time = time.time()
  A1 = np.random.random((500,500))
  u1,r = qr(A)
  end_time = datetime.now()
  time2 += time.time() - start_time
print('Average duration for SVD: {}'.format(time1/10000),'Average duration for QR: {}'.format(time2/10000))